name: we_personalization_flutter
description: WebEngage Flutter Personalization SDK enables seamless integration of dynamic, personalized inline views to enhance user engagement in your app.
version: 1.1.0
homepage: https://webengage.com/
repository: https://github.com/WebEngage/we-personalization-flutter

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.webengage.we_personalization_flutter
        pluginClass: WEPersonalizationPlugin
      ios:
        pluginClass: WEPersonalizationPlugin


